### PR TITLE
Audit service

### PR DESCRIPTION
**Pull request by RichardProsser**
Errm ... quite a lot!

### CODE REVIEW

**Comment by RichardProsser** [comment]
This incorporates audit logging and simplifies the configuration.

**Comment by ptrelease** [comment]
Why use production config rather than development config?  Check with Peasey if you want to go ahead with this.  Otherwise it seems OK.  Because its so much, i'm just starting up the VM and will give it a working test.

**Comment by RichardProsser** [comment]
I thought that ProductionConfig would be a suitable default setting, so that it doesn't have to be changed when the code is formally released. I should have highlighted that change - sorry.

Tests use TestConfig via 'envionment-test.sh' and developers can set whatever value is required via the shell environment.

**Comment by RichardProsser** [comment]
Paul,

I have restored the earlier setting but I still think that mine was correct!

I have also removed 'auditlogger.py', as that is now redundant; similar
code is to be found in Python_Logger.

Cheers,

Richard

**Pull request merged**
